# Generated by Django 3.1.4 on 2021-10-02 14:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('message', ckeditor.fields.RichTextField()),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=100)),
                ('link_url', models.CharField(blank=True, max_length=60)),
                ('order', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Important Link',
                'verbose_name_plural': 'Add Important Link',
            },
        ),
        migrations.CreateModel(
            name='NoticeAndEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_or_event', models.CharField(choices=[('1', 'Notice'), ('2', 'Events')], max_length=3)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('details', ckeditor.fields.RichTextField(blank=True)),
                ('upload_images', models.ImageField(blank=True, upload_to='images/notice_event_image')),
                ('notice_file', models.FileField(blank=True, upload_to='images/notice_file')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notice Event',
                'verbose_name_plural': 'Add Notice and Event',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.IntegerField(default=0, unique=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
            },
        ),
    ]
