# Generated by Django 3.1.4 on 2021-10-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_schoolprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_type', models.CharField(choices=[('1', 'Video Gallery'), ('2', 'Photo Gallery')], max_length=3)),
                ('gallery_for', models.CharField(blank=True, choices=[('1', 'Hostel'), ('2', 'Library'), ('3', 'Lab'), ('5', 'ID Card')], max_length=3)),
                ('gallery_title', models.CharField(blank=True, max_length=100)),
                ('gallery_images', models.ImageField(blank=True, upload_to='gallery')),
                ('gallery_link', models.TextField(blank=True)),
                ('gallery_order', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Info',
                'verbose_name_plural': 'Add Gallery',
            },
        ),
        migrations.CreateModel(
            name='SliderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True, max_length=5000)),
                ('images', models.ImageField(upload_to='slider')),
                ('slider_order', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
            },
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=160)),
                ('slugan', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('web_address', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(upload_to='company_info')),
                ('facebook_id', models.CharField(blank=True, max_length=200)),
                ('twitter_id', models.CharField(blank=True, max_length=200)),
                ('google_id', models.CharField(blank=True, max_length=200)),
                ('youtube_id', models.CharField(blank=True, max_length=200)),
                ('linkedin_id', models.CharField(blank=True, max_length=200)),
                ('copyright_name', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'School Profile',
                'verbose_name_plural': 'School Info',
            },
        ),
        migrations.AlterField(
            model_name='noticeandevent',
            name='notice_file',
            field=models.FileField(blank=True, upload_to='notice_file'),
        ),
        migrations.AlterField(
            model_name='noticeandevent',
            name='upload_images',
            field=models.ImageField(blank=True, upload_to='notice_event_image'),
        ),
    ]
