# Generated by Django 3.1.4 on 2022-02-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20211002_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolprofile',
            options={'verbose_name': 'School Profile', 'verbose_name_plural': 'School Profile'},
        ),
    ]
