# Generated by Django 3.1.4 on 2022-02-14 16:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220214_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_for', models.CharField(choices=[('1', 'Welcome Message'), ('2', 'Chairman Message'), ('3', 'Principal Message')], max_length=1)),
                ('details', ckeditor.fields.RichTextField(blank=True)),
                ('persion_images', models.ImageField(blank=True, upload_to='images/institute')),
                ('status', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Message',
                'verbose_name_plural': 'Academic Message',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_for', models.CharField(choices=[('1', 'Academic History'), ('2', 'At a Glance'), ('3', 'Why Study')], max_length=1)),
                ('details', ckeditor.fields.RichTextField(blank=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Content',
                'verbose_name_plural': 'Home Contents',
            },
        ),
        migrations.DeleteModel(
            name='WebsiteContent',
        ),
    ]
