# Generated by Django 3.1.4 on 2022-02-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20220221_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='content_for',
            field=models.CharField(choices=[('1', 'Our History'), ('2', 'About Us'), ('3', 'About School'), ('4', 'At a Glance')], max_length=1),
        ),
    ]
