# Generated by Django 3.1.4 on 2022-02-22 18:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20220221_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_for', models.CharField(choices=[('1', 'Welcome Message'), ('2', 'Chairman Message'), ('3', 'Principal Message'), ('4', 'President Message'), ('5', 'General Secretary Message')], max_length=1)),
                ('details', ckeditor.fields.RichTextField(blank=True)),
                ('persion_images', models.ImageField(blank=True, upload_to='images/institute')),
                ('status', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Message',
                'verbose_name_plural': 'Academic Message',
            },
        ),
        migrations.DeleteModel(
            name='AcademicMessage',
        ),
    ]
