# Generated by Django 3.1.4 on 2022-02-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20220223_0005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_info',
            new_name='MessageInfo',
        ),
    ]
