# Generated by Django 3.1.4 on 2022-02-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20220223_0007'),
        ('services', '0009_auto_20220222_2345'),
    ]

    operations = [
    ]
