# Generated by Django 3.1.4 on 2022-02-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_committeeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, unique=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batch',
            },
        ),
        migrations.AddField(
            model_name='committeeinfo',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.batch'),
            preserve_default=False,
        ),
    ]
