# Generated by Django 3.1.4 on 2022-02-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20220227_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeeinfo',
            options={'verbose_name': 'Committee Information', 'verbose_name_plural': 'Committee Informations'},
        ),
    ]
