# Generated by Django 3.1.4 on 2022-03-26 06:52

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20220326_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryinfo',
            name='gallery_link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
