# Generated by Django 3.1.4 on 2022-03-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20220326_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryinfo',
            name='gallery_link',
            field=models.CharField(max_length=250),
        ),
    ]
