# Generated by Django 3.1.4 on 2022-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20220326_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_title', models.CharField(blank=True, max_length=250)),
                ('video_url', models.CharField(max_length=250)),
                ('gallery_order', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Previous Event',
                'verbose_name_plural': 'Previous Event',
            },
        ),
    ]
