# Generated by Django 3.1.4 on 2022-04-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_previousevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=1)),
                ('present_address', models.CharField(blank=True, max_length=500)),
                ('permament_address', models.CharField(blank=True, max_length=500)),
                ('member_image', models.FileField(blank=True, upload_to='member_image')),
                ('password', models.CharField(max_length=12)),
                ('pass_inword', models.CharField(max_length=12)),
                ('order', models.IntegerField(default=0)),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('twitter', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.batch')),
            ],
            options={
                'verbose_name': 'All Member',
                'verbose_name_plural': 'All Members',
            },
        ),
    ]
