# Generated by Django 3.1.4 on 2022-04-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_allmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('qualifications', models.CharField(blank=True, max_length=150)),
                ('info_image', models.FileField(blank=True, upload_to='member_image')),
                ('order', models.IntegerField(default=0)),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('twitter', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'teacher students info',
                'verbose_name_plural': 'teacher students infos',
            },
        ),
    ]
