# Generated by Django 3.1.4 on 2022-04-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_allinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinfo',
            name='info_for',
            field=models.CharField(choices=[('1', 'teacher info'), ('2', 'student info')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
