# Generated by Django 3.1.4 on 2022-04-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_allinfo_info_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinfo',
            name='info_image',
            field=models.FileField(blank=True, upload_to='Info_image'),
        ),
    ]
