# Generated by Django 3.1.4 on 2022-04-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20220410_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
