# Generated by Django 3.1.4 on 2022-05-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_workgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=300)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=1)),
                ('present_address', models.CharField(blank=True, max_length=500)),
                ('permament_address', models.CharField(blank=True, max_length=500)),
                ('member_image', models.FileField(blank=True, upload_to='member_image')),
                ('order', models.IntegerField(default=0)),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('twitter', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.batch')),
            ],
        ),
    ]
