# Generated by Django 3.1.4 on 2022-05-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_userregistion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistion',
            old_name='member_image',
            new_name='register_image',
        ),
    ]
