# Generated by Django 3.1.4 on 2022-05-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_auto_20220523_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistion',
            old_name='reg_name',
            new_name='register_name',
        ),
    ]
