# Generated by Django 3.2.13 on 2022-06-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_auto_20220530_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistion',
            old_name='date_of_birth',
            new_name='date',
        ),
    ]
