# Generated by Django 3.2.13 on 2022-06-10 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_rename_date_of_birth_userregistion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistion',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.batch'),
        ),
    ]
