# Generated by Django 3.2.13 on 2022-06-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_alter_userregistion_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistion',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
