# Generated by Django 3.2.13 on 2022-06-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
