# Generated by Django 3.2.13 on 2022-06-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_auto_20220610_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact US'},
        ),
    ]
