# Generated by Django 3.2.13 on 2022-06-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('employee_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=7)),
                ('father_name', models.CharField(blank=True, max_length=40)),
                ('mother_name', models.CharField(blank=True, max_length=40)),
                ('emp_img', models.ImageField(blank=True, upload_to='emp_img')),
                ('emp_password', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=70)),
                ('blood_group', models.CharField(blank=True, choices=[('1', 'N/A'), ('2', 'A+'), ('3', 'A-'), ('4', 'B+'), ('5', 'B-'), ('6', 'AB+'), ('7', 'AB-'), ('8', 'O+'), ('9', 'O-')], max_length=2)),
                ('emp_religion', models.CharField(choices=[('1', 'Islam'), ('2', 'Christianity'), ('3', 'Hinduism'), ('4', 'Buddhism'), ('5', 'Chinese traditional religion'), ('6', 'African traditional religions')], max_length=1)),
                ('emp_gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=1)),
                ('desig_name', models.CharField(choices=[('1', 'Principal'), ('2', 'Employee'), ('3', 'IT Officer'), ('4', 'Vice Principal')], max_length=1)),
                ('fitness_details', models.TextField(blank=True)),
                ('medical_certificate', models.ImageField(blank=True, upload_to='medical_certificate')),
                ('emp_mobile', models.CharField(blank=True, max_length=15)),
                ('email_address', models.EmailField(blank=True, max_length=80)),
                ('join_date', models.DateField()),
                ('resign_date', models.DateField(auto_now_add=True)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(blank=True, max_length=40)),
                ('basic_salary', models.FloatField(default=0)),
                ('starting_salary', models.FloatField(blank=True, default=0)),
                ('present_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('added_by', models.CharField(blank=True, max_length=80)),
                ('is_teacher', models.BooleanField(default=0)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('insert_by', models.IntegerField(default=0)),
                ('update_by', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
